In [23]:
corpus =  ["you were born with potential",
"you were born with goodness and trust",
"you were born with ideals and dreams",
"you were born with greatness",
"you were born with wings",
"you are not meant for crawling so don't",
"you have wings",
"learn to use them and fly"
]

# Caculate the tokens frequency (TF) of each document

In [24]:
import nltk  
import numpy as np  
import random  
import string
import bs4 as bs  
import urllib.request  
import re  

In [25]:
## create tokens and caculate the frequency
wordfreq = {}
for sentence in corpus:
    print(sentence)
    tokens = nltk.word_tokenize(sentence)
    for token in tokens:
        if token not in wordfreq.keys():
            wordfreq[token] = 1
        else:
            wordfreq[token] += 1

you were born with potential
you were born with goodness and trust
you were born with ideals and dreams
you were born with greatness
you were born with wings
you are not meant for crawling so don't
you have wings
learn to use them and fly


In [35]:
wordfreq

{'you': 7,
 'were': 5,
 'born': 5,
 'with': 5,
 'potential': 1,
 'goodness': 1,
 'and': 3,
 'trust': 1,
 'ideals': 1,
 'dreams': 1,
 'greatness': 1,
 'wings': 2,
 'are': 1,
 'not': 1,
 'meant': 1,
 'for': 1,
 'crawling': 1,
 'so': 1,
 'do': 1,
 "n't": 1,
 'have': 1,
 'learn': 1,
 'to': 1,
 'use': 1,
 'them': 1,
 'fly': 1}

In [46]:
sentence_vectors = []
for sentence in corpus:
    sentence_tokens = nltk.word_tokenize(sentence)
    sent_vec = [0]*len(wordfreq.keys())
    for index, token in enumerate(wordfreq.keys()):
        if token not in sentence_tokens:
            sent_vec[index] = 0
        else:
            count = 0
            for temp in sentence_tokens:
                if token == temp:
                    count = count + 1
            sent_vec[index] = count
    sentence_vectors.append(sent_vec)
sentence_vectors = np.asarray(sentence_vectors)

In [47]:
sentence_vectors

array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 1, 1, 1]])

# Caculate the idf (inverse document frequency)

$$idf(term) = ln({\frac{1+n_{documents}}{1+tf(term)}})+1$$

In [36]:
import numpy as np

In [50]:
idf = []
for token in wordfreq.keys():
    idf.append(np.log((1+len(corpus)/(1+wordfreq[token]))) + 1)

In [51]:
idf

[1.6931471805599454,
 1.8472978603872034,
 1.8472978603872034,
 1.8472978603872034,
 2.6094379124341005,
 2.6094379124341005,
 2.09861228866811,
 2.6094379124341005,
 2.6094379124341005,
 2.6094379124341005,
 2.6094379124341005,
 2.2992829841302607,
 2.6094379124341005,
 2.6094379124341005,
 2.6094379124341005,
 2.6094379124341005,
 2.6094379124341005,
 2.6094379124341005,
 2.6094379124341005,
 2.6094379124341005,
 2.6094379124341005,
 2.6094379124341005,
 2.6094379124341005,
 2.6094379124341005,
 2.6094379124341005,
 2.6094379124341005]

In [48]:
sentence_vectors.shape

(8, 26)

In [52]:
idf = np.array(idf)

In [53]:
idf.shape

(26,)

# Caculate tf-idf embedding of sentence

$$TF-IDF(document)=tf*idf$$

In [54]:
tf_idf = sentence_vectors*idf

In [55]:
tf_idf.shape

(8, 26)

In [56]:
tf_idf

array([[1.69314718, 1.84729786, 1.84729786, 1.84729786, 2.60943791,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.69314718, 1.84729786, 1.84729786, 1.84729786, 0.        ,
        2.60943791, 2.09861229, 2.60943791, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.69314718, 1.84729786, 1.84729786, 1.84729786, 0.        ,
        0.        , 2.09861229, 0.        , 2.60943791, 2.60943791,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
      

In [58]:
## normalize tf_idf
from sklearn.preprocessing import Normalizer
sentence_tf_idf = Normalizer(norm='l2').fit_transform(tf_idf)

In [59]:
sentence_tf_idf

array([[0.37942116, 0.41396513, 0.41396513, 0.41396513, 0.58475481,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.30347827, 0.33110811, 0.33110811, 0.33110811, 0.        ,
        0.46771345, 0.3761535 , 0.46771345, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.30347827, 0.33110811, 0.33110811, 0.33110811, 0.        ,
        0.        , 0.3761535 , 0.        , 0.46771345, 0.46771345,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
      

In [60]:
corpus[0]

'you were born with potential'

In [61]:
sentence_tf_idf[0]

array([0.37942116, 0.41396513, 0.41396513, 0.41396513, 0.58475481,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])