In [1]:
import numpy as np
from tqdm import tqdm_notebook
import re

# Chuẩn bị dữ liệu 

In [27]:
def tokenize(text):
    # obtains tokens with a least 1 alphabet
    pattern = re.compile(r'[A-Za-z]+[\w^\']*|[\w^\']*[A-Za-z]+[\w^\']*')
    return pattern.findall(text.lower())

def mapping(tokens):
    word_to_id = dict()
    id_to_word = dict()

    for i, token in enumerate(set(tokens)):
        word_to_id[token] = i
        id_to_word[i] = token

    return word_to_id, id_to_word

def generate_training_data(tokens, word_to_id, window_size):
    N = len(tokens)
    M = len(set(tokens))
    X, Y = [], []

    for i in range(N):
        nbr_inds = list(range(max(0, i - window_size), i)) + \
                   list(range(i + 1, min(N, i + window_size + 1)))
        ## khac biet chinh cua CBOW va Skip gram model
        x = np.zeros(M)
        y = np.zeros(M)
        for j in nbr_inds:
            x[word_to_id[tokens[j]]] = 1
        y[word_to_id[tokens[j]]] = 1
        X.append(x)
        Y.append(y)
            
    X = np.array(X)
#     X = np.expand_dims(X, axis=0)
    Y = np.array(Y)
#     Y = np.expand_dims(Y, axis=0)
            
    return X, Y

In [28]:
doc = "After the deduction of the costs of investing, " \
      "beating the stock market is a loser's game."
tokens = tokenize(doc)
tokens

['after',
 'the',
 'deduction',
 'of',
 'the',
 'costs',
 'of',
 'investing',
 'beating',
 'the',
 'stock',
 'market',
 'is',
 'a',
 "loser's",
 'game']

In [29]:
word_to_id, id_to_word = mapping(tokens)
word_to_id

{'of': 0,
 'investing': 1,
 'the': 2,
 'costs': 3,
 'deduction': 4,
 'beating': 5,
 'stock': 6,
 'is': 7,
 'a': 8,
 'game': 9,
 'market': 10,
 'after': 11,
 "loser's": 12}

In [30]:
id_to_word

{0: 'of',
 1: 'investing',
 2: 'the',
 3: 'costs',
 4: 'deduction',
 5: 'beating',
 6: 'stock',
 7: 'is',
 8: 'a',
 9: 'game',
 10: 'market',
 11: 'after',
 12: "loser's"}

In [31]:
X, Y = generate_training_data(tokens, word_to_id, 3)
X.shape

(16, 13)

In [32]:
X

array([[1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1.]])

In [33]:
Y

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Huấn luyện 

In [34]:
from keras.models import Sequential
from keras.layers import Dense, Activation

Using TensorFlow backend.
/home/dan/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/dan/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/dan/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/dan/.local/lib/python3.6/site-packages/tensorflow/python/framework/d

In [35]:
X_train = X
Y_train = Y
size_of_vocab = X_train.shape[1]
size_of_vocab

13

In [36]:
emb_size = 112

In [37]:
model = Sequential()
model.add(Dense(emb_size, activation='linear', input_dim=size_of_vocab ))
model.add(Dense(size_of_vocab, activation='linear'))
model.add(Activation("softmax"))

In [38]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 112)               1568      
_________________________________________________________________
dense_2 (Dense)              (None, 13)                1469      
_________________________________________________________________
activation_1 (Activation)    (None, 13)                0         
Total params: 3,037
Trainable params: 3,037
Non-trainable params: 0
_________________________________________________________________


In [39]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [40]:
model.fit(X_train, Y_train, epochs=1000, batch_size=10)

Epoch 1/1000
16/16 [==============================] - 1s 69ms/step - loss: 0.2804 - acc: 0.9231
Epoch 2/1000
16/16 [==============================] - 0s 392us/step - loss: 0.2753 - acc: 0.9231
Epoch 3/1000
16/16 [==============================] - 0s 313us/step - loss: 0.2704 - acc: 0.9231
Epoch 4/1000
16/16 [==============================] - 0s 272us/step - loss: 0.2655 - acc: 0.9231
Epoch 5/1000
16/16 [==============================] - 0s 441us/step - loss: 0.2605 - acc: 0.9231
Epoch 6/1000
16/16 [==============================] - 0s 336us/step - loss: 0.2559 - acc: 0.9231
Epoch 7/1000
16/16 [==============================] - 0s 423us/step - loss: 0.2510 - acc: 0.9231
Epoch 8/1000
16/16 [==============================] - 0s 336us/step - loss: 0.2464 - acc: 0.9231
Epoch 9/1000
16/16 [==============================] - 0s 503us/step - loss: 0.2415 - acc: 0.9231
Epoch 10/1000
16/16 [==============================] - 0s 419us/step - loss: 0.2372 - acc: 0.9231
Epoch 11/1000
16/16 [=========

16/16 [==============================] - 0s 403us/step - loss: 0.0676 - acc: 0.9712
Epoch 85/1000
16/16 [==============================] - 0s 235us/step - loss: 0.0666 - acc: 0.9712
Epoch 86/1000
16/16 [==============================] - 0s 332us/step - loss: 0.0657 - acc: 0.9712
Epoch 87/1000
16/16 [==============================] - 0s 301us/step - loss: 0.0647 - acc: 0.9760
Epoch 88/1000
16/16 [==============================] - 0s 248us/step - loss: 0.0637 - acc: 0.9760
Epoch 89/1000
16/16 [==============================] - 0s 383us/step - loss: 0.0629 - acc: 0.9808
Epoch 90/1000
16/16 [==============================] - 0s 229us/step - loss: 0.0620 - acc: 0.9760
Epoch 91/1000
16/16 [==============================] - 0s 226us/step - loss: 0.0611 - acc: 0.9760
Epoch 92/1000
16/16 [==============================] - 0s 319us/step - loss: 0.0602 - acc: 0.9808
Epoch 93/1000
16/16 [==============================] - 0s 321us/step - loss: 0.0594 - acc: 0.9808
Epoch 94/1000
16/16 [=============

16/16 [==============================] - 0s 270us/step - loss: 0.0246 - acc: 0.9952
Epoch 168/1000
16/16 [==============================] - ETA: 0s - loss: 0.0191 - acc: 1.000 - 0s 272us/step - loss: 0.0242 - acc: 1.0000
Epoch 169/1000
16/16 [==============================] - 0s 271us/step - loss: 0.0240 - acc: 1.0000
Epoch 170/1000
16/16 [==============================] - 0s 226us/step - loss: 0.0237 - acc: 1.0000
Epoch 171/1000
16/16 [==============================] - 0s 403us/step - loss: 0.0235 - acc: 1.0000
Epoch 172/1000
16/16 [==============================] - 0s 246us/step - loss: 0.0231 - acc: 1.0000
Epoch 173/1000
16/16 [==============================] - 0s 241us/step - loss: 0.0230 - acc: 1.0000
Epoch 174/1000
16/16 [==============================] - 0s 357us/step - loss: 0.0228 - acc: 1.0000
Epoch 175/1000
16/16 [==============================] - 0s 230us/step - loss: 0.0225 - acc: 1.0000
Epoch 176/1000
16/16 [==============================] - 0s 279us/step - loss: 0.0222 -

16/16 [==============================] - 0s 660us/step - loss: 0.0109 - acc: 1.0000
Epoch 249/1000
16/16 [==============================] - 0s 363us/step - loss: 0.0109 - acc: 1.0000
Epoch 250/1000
16/16 [==============================] - 0s 240us/step - loss: 0.0108 - acc: 1.0000
Epoch 251/1000
16/16 [==============================] - 0s 230us/step - loss: 0.0107 - acc: 1.0000
Epoch 252/1000
16/16 [==============================] - 0s 287us/step - loss: 0.0106 - acc: 1.0000
Epoch 253/1000
16/16 [==============================] - 0s 450us/step - loss: 0.0105 - acc: 1.0000
Epoch 254/1000
16/16 [==============================] - 0s 252us/step - loss: 0.0104 - acc: 1.0000
Epoch 255/1000
16/16 [==============================] - 0s 315us/step - loss: 0.0103 - acc: 1.0000
Epoch 256/1000
16/16 [==============================] - 0s 314us/step - loss: 0.0102 - acc: 1.0000
Epoch 257/1000
16/16 [==============================] - 0s 234us/step - loss: 0.0101 - acc: 1.0000
Epoch 258/1000
16/16 [===

16/16 [==============================] - 0s 376us/step - loss: 0.0057 - acc: 1.0000
Epoch 331/1000
16/16 [==============================] - 0s 321us/step - loss: 0.0057 - acc: 1.0000
Epoch 332/1000
16/16 [==============================] - 0s 290us/step - loss: 0.0057 - acc: 1.0000
Epoch 333/1000
16/16 [==============================] - 0s 412us/step - loss: 0.0056 - acc: 1.0000
Epoch 334/1000
16/16 [==============================] - 0s 491us/step - loss: 0.0056 - acc: 1.0000
Epoch 335/1000
16/16 [==============================] - 0s 464us/step - loss: 0.0055 - acc: 1.0000
Epoch 336/1000
16/16 [==============================] - 0s 464us/step - loss: 0.0055 - acc: 1.0000
Epoch 337/1000
16/16 [==============================] - 0s 401us/step - loss: 0.0055 - acc: 1.0000
Epoch 338/1000
16/16 [==============================] - 0s 408us/step - loss: 0.0054 - acc: 1.0000
Epoch 339/1000
16/16 [==============================] - 0s 522us/step - loss: 0.0054 - acc: 1.0000
Epoch 340/1000
16/16 [===

16/16 [==============================] - 0s 466us/step - loss: 0.0034 - acc: 1.0000
Epoch 413/1000
16/16 [==============================] - 0s 415us/step - loss: 0.0034 - acc: 1.0000
Epoch 414/1000
16/16 [==============================] - 0s 465us/step - loss: 0.0034 - acc: 1.0000
Epoch 415/1000
16/16 [==============================] - 0s 629us/step - loss: 0.0034 - acc: 1.0000
Epoch 416/1000
16/16 [==============================] - 0s 300us/step - loss: 0.0034 - acc: 1.0000
Epoch 417/1000
16/16 [==============================] - 0s 352us/step - loss: 0.0033 - acc: 1.0000
Epoch 418/1000
16/16 [==============================] - 0s 519us/step - loss: 0.0033 - acc: 1.0000
Epoch 419/1000
16/16 [==============================] - 0s 231us/step - loss: 0.0033 - acc: 1.0000
Epoch 420/1000
16/16 [==============================] - 0s 468us/step - loss: 0.0033 - acc: 1.0000
Epoch 421/1000
16/16 [==============================] - 0s 316us/step - loss: 0.0033 - acc: 1.0000
Epoch 422/1000
16/16 [===

16/16 [==============================] - 0s 335us/step - loss: 0.0023 - acc: 1.0000
Epoch 495/1000
16/16 [==============================] - 0s 250us/step - loss: 0.0023 - acc: 1.0000
Epoch 496/1000
16/16 [==============================] - 0s 317us/step - loss: 0.0022 - acc: 1.0000
Epoch 497/1000
16/16 [==============================] - 0s 288us/step - loss: 0.0022 - acc: 1.0000
Epoch 498/1000
16/16 [==============================] - 0s 255us/step - loss: 0.0022 - acc: 1.0000
Epoch 499/1000
16/16 [==============================] - 0s 284us/step - loss: 0.0022 - acc: 1.0000
Epoch 500/1000
16/16 [==============================] - 0s 321us/step - loss: 0.0022 - acc: 1.0000
Epoch 501/1000
16/16 [==============================] - 0s 246us/step - loss: 0.0022 - acc: 1.0000
Epoch 502/1000
16/16 [==============================] - 0s 233us/step - loss: 0.0022 - acc: 1.0000
Epoch 503/1000
16/16 [==============================] - 0s 411us/step - loss: 0.0022 - acc: 1.0000
Epoch 504/1000
16/16 [===

16/16 [==============================] - 0s 288us/step - loss: 0.0016 - acc: 1.0000
Epoch 577/1000
16/16 [==============================] - 0s 256us/step - loss: 0.0016 - acc: 1.0000
Epoch 578/1000
16/16 [==============================] - 0s 359us/step - loss: 0.0016 - acc: 1.0000
Epoch 579/1000
16/16 [==============================] - 0s 306us/step - loss: 0.0016 - acc: 1.0000
Epoch 580/1000
16/16 [==============================] - 0s 277us/step - loss: 0.0016 - acc: 1.0000
Epoch 581/1000
16/16 [==============================] - 0s 383us/step - loss: 0.0016 - acc: 1.0000
Epoch 582/1000
16/16 [==============================] - 0s 231us/step - loss: 0.0015 - acc: 1.0000
Epoch 583/1000
16/16 [==============================] - 0s 229us/step - loss: 0.0015 - acc: 1.0000
Epoch 584/1000
16/16 [==============================] - 0s 308us/step - loss: 0.0015 - acc: 1.0000
Epoch 585/1000
16/16 [==============================] - 0s 260us/step - loss: 0.0015 - acc: 1.0000
Epoch 586/1000
16/16 [===

16/16 [==============================] - 0s 310us/step - loss: 0.0012 - acc: 1.0000
Epoch 658/1000
16/16 [==============================] - 0s 225us/step - loss: 0.0012 - acc: 1.0000
Epoch 659/1000
16/16 [==============================] - 0s 339us/step - loss: 0.0012 - acc: 1.0000
Epoch 660/1000
16/16 [==============================] - 0s 298us/step - loss: 0.0012 - acc: 1.0000
Epoch 661/1000
16/16 [==============================] - 0s 219us/step - loss: 0.0012 - acc: 1.0000
Epoch 662/1000
16/16 [==============================] - 0s 344us/step - loss: 0.0012 - acc: 1.0000
Epoch 663/1000
16/16 [==============================] - 0s 432us/step - loss: 0.0011 - acc: 1.0000
Epoch 664/1000
16/16 [==============================] - 0s 410us/step - loss: 0.0011 - acc: 1.0000
Epoch 665/1000
16/16 [==============================] - 0s 714us/step - loss: 0.0011 - acc: 1.0000
Epoch 666/1000
16/16 [==============================] - 0s 356us/step - loss: 0.0011 - acc: 1.0000
Epoch 667/1000
16/16 [===

16/16 [==============================] - 0s 293us/step - loss: 8.9615e-04 - acc: 1.0000
Epoch 739/1000
16/16 [==============================] - 0s 307us/step - loss: 8.9392e-04 - acc: 1.0000
Epoch 740/1000
16/16 [==============================] - 0s 243us/step - loss: 8.9076e-04 - acc: 1.0000
Epoch 741/1000
16/16 [==============================] - 0s 348us/step - loss: 8.8885e-04 - acc: 1.0000
Epoch 742/1000
16/16 [==============================] - 0s 393us/step - loss: 8.8648e-04 - acc: 1.0000
Epoch 743/1000
16/16 [==============================] - 0s 391us/step - loss: 8.8257e-04 - acc: 1.0000
Epoch 744/1000
16/16 [==============================] - 0s 286us/step - loss: 8.8018e-04 - acc: 1.0000
Epoch 745/1000
16/16 [==============================] - 0s 221us/step - loss: 8.7879e-04 - acc: 1.0000
Epoch 746/1000
16/16 [==============================] - 0s 349us/step - loss: 8.7404e-04 - acc: 1.0000
Epoch 747/1000
16/16 [==============================] - 0s 318us/step - loss: 8.7224e-04

16/16 [==============================] - 0s 251us/step - loss: 7.0755e-04 - acc: 1.0000
Epoch 818/1000
16/16 [==============================] - 0s 432us/step - loss: 7.0537e-04 - acc: 1.0000
Epoch 819/1000
16/16 [==============================] - 0s 288us/step - loss: 7.0353e-04 - acc: 1.0000
Epoch 820/1000
16/16 [==============================] - 0s 225us/step - loss: 7.0177e-04 - acc: 1.0000
Epoch 821/1000
16/16 [==============================] - 0s 365us/step - loss: 7.0022e-04 - acc: 1.0000
Epoch 822/1000
16/16 [==============================] - 0s 398us/step - loss: 6.9815e-04 - acc: 1.0000
Epoch 823/1000
16/16 [==============================] - 0s 384us/step - loss: 6.9686e-04 - acc: 1.0000
Epoch 824/1000
16/16 [==============================] - 0s 318us/step - loss: 6.9369e-04 - acc: 1.0000
Epoch 825/1000
16/16 [==============================] - 0s 291us/step - loss: 6.9165e-04 - acc: 1.0000
Epoch 826/1000
16/16 [==============================] - 0s 396us/step - loss: 6.9013e-04

16/16 [==============================] - 0s 232us/step - loss: 5.6907e-04 - acc: 1.0000
Epoch 897/1000
16/16 [==============================] - 0s 318us/step - loss: 5.6777e-04 - acc: 1.0000
Epoch 898/1000
16/16 [==============================] - 0s 372us/step - loss: 5.6655e-04 - acc: 1.0000
Epoch 899/1000
16/16 [==============================] - 0s 215us/step - loss: 5.6495e-04 - acc: 1.0000
Epoch 900/1000
16/16 [==============================] - 0s 410us/step - loss: 5.6339e-04 - acc: 1.0000
Epoch 901/1000
16/16 [==============================] - 0s 284us/step - loss: 5.6217e-04 - acc: 1.0000
Epoch 902/1000
16/16 [==============================] - 0s 209us/step - loss: 5.6086e-04 - acc: 1.0000
Epoch 903/1000
16/16 [==============================] - 0s 358us/step - loss: 5.5942e-04 - acc: 1.0000
Epoch 904/1000
16/16 [==============================] - 0s 303us/step - loss: 5.5793e-04 - acc: 1.0000
Epoch 905/1000
16/16 [==============================] - 0s 241us/step - loss: 5.5651e-04

16/16 [==============================] - 0s 314us/step - loss: 4.6599e-04 - acc: 1.0000
Epoch 976/1000
16/16 [==============================] - 0s 312us/step - loss: 4.6497e-04 - acc: 1.0000
Epoch 977/1000
16/16 [==============================] - 0s 216us/step - loss: 4.6420e-04 - acc: 1.0000
Epoch 978/1000
16/16 [==============================] - 0s 390us/step - loss: 4.6306e-04 - acc: 1.0000
Epoch 979/1000
16/16 [==============================] - 0s 406us/step - loss: 4.6143e-04 - acc: 1.0000
Epoch 980/1000
16/16 [==============================] - 0s 253us/step - loss: 4.6030e-04 - acc: 1.0000
Epoch 981/1000
16/16 [==============================] - 0s 561us/step - loss: 4.5894e-04 - acc: 1.0000
Epoch 982/1000
16/16 [==============================] - 0s 233us/step - loss: 4.5880e-04 - acc: 1.0000
Epoch 983/1000
16/16 [==============================] - 0s 234us/step - loss: 4.5716e-04 - acc: 1.0000
Epoch 984/1000
16/16 [==============================] - 0s 390us/step - loss: 4.5584e-04

# Get trained word embedding weights

In [41]:
Word_embeding = model.get_weights()[0]

In [42]:
Word_embeding

array([[ 0.10469833, -0.18691468, -0.2306864 , ...,  0.2430629 ,
         0.04024751,  0.2521314 ],
       [ 0.42571145,  0.21114814,  0.48579574, ...,  0.24157873,
         0.30715165,  0.00424309],
       [-0.10106903, -0.00338911,  0.05663247, ...,  0.13397998,
        -0.02394506,  0.3257176 ],
       ...,
       [ 0.4182448 , -0.345889  , -0.10749426, ..., -0.26727575,
        -0.60737157, -0.1756833 ],
       [-0.0374453 ,  0.06897879, -0.46229997, ...,  0.37971088,
         0.49988136,  0.1074423 ],
       [-0.19736049,  0.23171805,  0.00294565, ..., -0.35424685,
         0.37158552, -0.09330902]], dtype=float32)

# Testing get embedding of the word "after"

In [47]:
X_test = np.zeros(13)
X_test[11] = 1
X_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.])

In [48]:
id_to_word[np.argmax(X_test)]

'after'

In [49]:
np.dot(np.expand_dims(X_test, 0), Word_embeding)

array([[-3.74452993e-02,  6.89787865e-02, -4.62299973e-01,
        -4.72458541e-01,  7.16512417e-03,  2.59430557e-01,
        -4.83964264e-01, -2.87864748e-02, -1.12279348e-01,
         4.94896889e-01, -1.52125001e-01,  5.06921768e-01,
         4.45361733e-02,  3.44887942e-01, -1.91549957e-01,
         1.30135015e-01,  7.28021003e-03, -1.47743136e-01,
        -2.92162359e-01,  4.70345438e-01,  5.80472827e-01,
         1.37871519e-01,  2.41578653e-01, -1.63500860e-01,
        -1.56682834e-01,  4.23217714e-01, -1.24221802e-01,
        -3.15191627e-01,  7.45055750e-02,  3.69175613e-01,
        -5.41607034e-04, -2.69309372e-01,  3.09974551e-01,
         1.22762918e-01, -4.54177847e-03,  4.88289893e-01,
         4.03012753e-01, -3.37154478e-01,  9.56770256e-02,
         5.66732921e-02,  2.10539833e-01,  4.35633659e-02,
        -5.42566180e-02,  4.04731855e-02, -1.52658924e-01,
        -3.10137402e-02,  2.85762906e-01,  8.78265798e-02,
        -3.39952976e-01, -2.34640449e-01, -5.95266409e-0

In [50]:
np.dot(np.expand_dims(X_test, 0), Word_embeding).shape

(1, 112)